### ISSUE TITLE
Great framework, what is the plan for the future?

### ISSUE THREAD

**Issue by nosslin579** [greenjoe/sergeants#2]
I played around with your framework and it looks great. Do you have any plans for more features? I was thinking of a mock server that would take two or more pl.joegreen.sergeants.framework.Bot and run a game without delays. That means I cloud ran a lot of games very fast. This would be handy if using evolutionary programming.

//Christian

**Comment by nosslin579** [comment]
So what I mean is not going via socket.io as that would probably slow it down and it would also be more complicated to implement.

**Comment by nosslin579** [comment]
After digging in the code a I think it is better to implement a Socket. That would still bypass socket.io.

**Comment by nosslin579** [comment]
Maybe it is easier to implement `Socket`?

**Comment by greenjoe** [comment]
Hello, thank you for your kind words. I'm glad you liked it. 

I know what you mean and I agree it would be possible to implement a mock generalsio server by implementing the Socket interface. It would be probably even better to feed game state updates into bots directly, but as for now there are no convenient builders for GameState class in the project. 

I'm sorry but I don't think it is inside my scope of interest and I don't think I'm going to put my time into implementing it myself (I could help if someone decided to lead the effort).

I've just seen on the generalsio bot discord https://discordapp.com/channels/261627238972129283/261627238972129283 that user danielvf wrote:

> I'm working on bot running framework
> To run local games, show debugging information, and run bots against the server
So you'll have a list of local bots on the right - you can add and remove them
> Then they fight it out
> That way you have a much faster learning curve than only playing on the server
> Planning on having local bot tournaments as well
> So you can see if V47 is really better than V46
> For phase zero of getting started, I'm going to run it all in browser.
> Restricted to javascript only bots

I think that's exactly what you need, you may want to get in touch with him :) 

Best regards,
Paweł

**Comment by nosslin579** [comment]
I have done some effort to implement a mock server. I went with the straight to `Bot` alternative. It can be changed later.
I will have a look at Danielvf's frameworkt but I prefer Java, also your code has nice structure and it is easy readable.

**Comment by greenjoe** [comment]
@nosslin579 Wow, awesome :) if you need any help from me, let me know
