### ISSUE TITLE
Simulated server

### ISSUE THREAD

**Issue by nosslin579** [greenjoe/sergeants#6]
I have done some work on the simulated server and it is not done but it is possible too run a game with two bots and you can view a replay, so it is ready for an initial commit.
Major parts that are not implemented yet are:

- random map generator
- client fogging
- sending GameStartApiResponse.java
- sending GameLostApiResponse.java

And then there is minor issues.

I want your opinion on where to commit. To a separate package, different module or its own repo?

**Comment by greenjoe** [comment]
I'd go for just another package, like pl.joegreen.sergeants.simulation, unless you added some very heavy maven dependencies (for example spring) - in that case it might be better to create a new maven module.
